#這個檔案的作用是：建立功能列表

#===============這些是LINE提供的功能套組，先用import叫出來=============
from linebot import (LineBotApi, WebhookHandler)
from linebot.exceptions import (InvalidSignatureError)
from linebot.models import *
#===============LINEAPI=============================================

#以下是本檔案的內容本文

#1.建立旋轉木馬訊息，名為function_list(未來可以叫出此函數來使用)
#function_list的括號內是設定此函數呼叫時需要給函數的參數有哪些

def function_list():
    message = TemplateSendMessage(
        alt_text='功能列表',
        template=CarouselTemplate(
            columns=[
                CarouselColumn(
                    thumbnail_image_url='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQkl5qgGtBxZbBu921rynn7HN7C7JaD_Hbi5cMMV5gEgQu2mE-rIw',
                    title='關於Maso百貨',
                    text='關於Maso百貨',
                    actions=[
                        MessageTemplateAction(
                            label='關於Maso百貨',
                            text='關於Maso百貨'
                        ),
                        URITemplateAction(
                            label='關於Maso百貨',
                            uri='https://tw.shop.com/maso0310'
                        )
                    ]
                ),
                CarouselColumn(
                    thumbnail_image_url='https://www.youtaker.com/video2015/promo/images/promo-vip.png',
                    title='會員好康資訊',
                    text='會員好康資訊',
                    actions=[
                        MessageTemplateAction(
                            label='會員好康資訊',
                            text='會員好康資訊'
                        ),
                        URITemplateAction(
                            label='會員好康資訊',
                            uri='https://tw.shop.com/nbts/create-myaccount.xhtml?returnurl=https%3A%2F%2Ftw.shop.com%2F'
                        )
                    ]
                ),
                CarouselColumn(
                    thumbnail_image_url='https://img.shop.com/Image/Images/11module/MABrands/opc3Chews_usa_32979_LogoTreatment_200x75.svg',
                    title='獨家商品資訊',
                    text='獨家商品資訊',
                    actions=[
                        MessageTemplateAction(
                            label='獨家商品資訊',
                            text='獨家商品資訊'
                        ),
                        URITemplateAction(
                            label='獨家商品資訊',
                            uri='https://tw.shop.com/info/our-brands'
                        )
                    ]
                ),
                CarouselColumn(
                    thumbnail_image_url='https://img.shop.com/Image/featuredhotdeal/GOMAJI1551245496503.jpg',
                    title='優惠資訊',
                    text='優惠資訊',
                    actions=[
                        MessageTemplateAction(
                            label='優惠資訊',
                            text='優惠資訊'
                        ),
                        URITemplateAction(
                            label='優惠資訊',
                            uri='https://tw.shop.com/hot-deals'
                        )
                    ]
                ),
                CarouselColumn(
                    thumbnail_image_url='https://img.shop.com/Image/featuredhotdeal/Carrefour1551245288925.jpg',
                    title='最新消息',
                    text='最新消息',
                    actions=[
                        MessageTemplateAction(
                            label='最新消息',
                            text='最新消息'
                        ),
                        URITemplateAction(
                            label='最新消息',
                            uri='https://tw.shop.com/hot-deals'
                        )
                    ]
                ),
                CarouselColumn(
                    thumbnail_image_url='https://scontent-sjc3-1.xx.fbcdn.net/v/t1.0-1/p320x320/50934385_2553136691368417_7766092240367124480_n.jpg?_nc_cat=109&_nc_ht=scontent-sjc3-1.xx&oh=c144a6b45450781ccaf258beb40bc53e&oe=5D228BF1',
                    title='每日新知',
                    text='每日新知',
                    actions=[
                        MessageTemplateAction(
                            label='每日新知',
                            text='每日新知'
                        ),
                        URITemplateAction(
                            label='每日新知',
                            uri='https://www.youtube.com/channel/UCpzVAEwEs9AwT2uAOZuxaRQ?view_as=subscriber'
                        )
                    ]
                ),
                CarouselColumn(
                    thumbnail_image_url='https://www.wecooperation.com/makemoney/%E7%9F%A5%E5%90%8D%E5%A4%A5%E4%BC%B4%E5%95%86%E5%BA%97.png',
                    title='好店分享',
                    text='好店分享',
                    actions=[
                        MessageTemplateAction(
                            label='好店分享',
                            text='好店分享'
                        ),
                        URITemplateAction(
                            label='好店分享',
                            uri='https://tw.shop.com/stores-a-z'
                        )
                    ]
                ),
                CarouselColumn(
                    thumbnail_image_url='https://img.shop.com/Image/Images/landingPages/ps-recruit/twn-ps-recruit-header.jpg',
                    title='招商說明',
                    text='招商說明',
                    actions=[
                        MessageTemplateAction(
                            label='招商說明',
                            text='招商說明'
                        ),
                        URITemplateAction(
                            label='招商說明',
                            uri='https://tw.shop.com/ps_recruit_intro-v.xhtml?tkr=180530162209'
                        )
                    ]
                ),
                CarouselColumn(
                    thumbnail_image_url='https://images.marketamerica.com/site/br/images/logos/awards/torch-award-ethics-2018.jpg',
                    title='微型創業資訊',
                    text='微型創業資訊',
                    actions=[
                        MessageTemplateAction(
                            label='微型創業資訊',
                            text='微型創業資訊'
                        ),
                        URITemplateAction(
                            label='微型創業資訊',
                            uri='https://www.marketamerica.com/?localeCode=zh-Hant&redirect=true'
                        )
                    ]
                ),
                CarouselColumn(
                    thumbnail_image_url='https://scontent-sjc3-1.xx.fbcdn.net/v/t1.0-1/p320x320/50934385_2553136691368417_7766092240367124480_n.jpg?_nc_cat=109&_nc_ht=scontent-sjc3-1.xx&oh=c144a6b45450781ccaf258beb40bc53e&oe=5D228BF1',
                    title='聯繫Maso本人',
                    text='聯繫Maso本人',
                    actions=[
                        MessageTemplateAction(
                            label='聯繫Maso本人',
                            text='聯繫Maso本人'
                        ),
                        URITemplateAction(
                            label='聯繫Maso本人',
                            uri='https://line.me/ti/p/KeRocPY6PP'
                        )
                    ]
                )
            ]
        )
    )
    return message